[workspace]
channels = ["hydrocomputing", "conda-forge"]
platforms = ["osx-arm64","linux-64"]
preview = ["pixi-build"]

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[dependencies]
python = "3.14.*"
matplotlib = "*"
pandas = "*"
pymf6 = "*"
phreeqpy = "*"
gfortran = ">=15.2.0,<15.3"
ipython = ">=9.8.0,<10"
modflowapi = ">=0.3.0,<0.4"
pymf6-tools = ">=0.1.3,<0.2"
jupyterlab = ">=4.5.1,<5"
typer = ">=0.21.1,<0.22"
pylint = "*"
setuptools_scm = "*"
pip = "*"

[pypi-dependencies]
# use `pixi run install-editable` to install rtmf6 in editable mode via pip
# otherwise dependencies from PyPi will override conda dependencies
# rtmf6 = { path = ".", editable = true }
# phreeqcrm must be at least 0.0.17
# use `pixi run install-phreeqcrm` to install phreeqcrm from PyPi
# phreeqcrm is a dependency of rtmf6 of phreeqpy, and will be installed
# from conda-forge, which currently only provides version 0.0.16

[feature.build.dependencies]
twine = ">=5.0.0,<5.1"

[feature.test.dependencies]
pytest = "*"
pytest-md = "*"
pytest-mock = ">=3.15.1,<4"

[feature.docs.dependencies]
myst-parser = ">=3.0,<4"
sphinx = ">=7.0,<8"
myst-nb = ">=1.1,<2"
jupyterlab = ">=4.5.2,<5"
sphinx-autodoc-typehints = ">=2.0,<3"
furo = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
sphinxcontrib-bibtex = "*"
ansi2html = ">=1.9.2,<2"
rtmf6 = "*"

# General tasks
[tasks.install-editable]
cmd = "pixi remove rtmf6 && pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
description = "install rtmf6 via pip"

[tasks.uninstall-editable]
cmd = "pip uninstall -y rtmf6 && pixi install"
description = "uninstall rtmf6 via pip"

[tasks.install-phreeqcrm]
cmd = "pip install -U phreeqcrm"
description = "Install phreeqcrm from PyPi. Note: phreeqcrm must be at least version 0.0.17 to work with rtmf6."

[tasks.start]
cmd = "rtmf6"
description = "Start rtmf6"

[tasks.show-version]
cmd = "python -m setuptools_scm"
description = "Show version"

[tasks.update-version]
cmd = "python -m setuptools_scm --force-write-version-files"
description = "Update version files"

# Documentation tasks
# Tasks for documentation are defined in the [feature.docs.tasks] section below.
[feature.docs.tasks.docs-build]
cmd = "sphinx-build -b html source _build/html"
cwd = "docs"
description = "Build documentation"

[feature.docs.tasks.docs-clean]
cmd = "rm -rf _build"
cwd = "docs"
description = "Clean documentation build"

[feature.docs.tasks.docs-serve]
cmd = "python -m http.server -d _build/html 8907"
cwd = "docs"
description = "Serve documentation locally"

[feature.docs.tasks.docs-deploy]
cmd = "zsh deploy_docs.sh"
cwd = "docs/.deploy"
description = "Deploy documentation to https://docs.rtmf6.com/."

[feature.docs.tasks.docs-make-cli-doc]
cmd = "typer rtmf6.main utils docs --output README.md"
cwd = "docs/source/users_guide"
description = "Generate CLI documentation"

# Tests tasks
[feature.test.tasks.test-report]
cmd = "pytest --md=report.md"
description = "Run all tests with pytest and generate a report in report.md"

# Build tasks
[feature.build.tasks.build-wheel]
cmd = "uv build"
description = "Build a Python wheel for PyPi upload"

[feature.build.tasks.pypi-upload]
cmd = "python -m twine upload --verbose --config-file=$PYPI_HYDRO"
description = "Upload to PyPi"

# Build conda package with Pixi
[package]
name = "rtmf6"
version = "0.1.0"  # TODO: make dynamic

[package.build]
backend = { name = "pixi-build-python", version = "0.4.*" }

[package.host-dependencies]
setuptools = "*"

[package.run-dependencies]
rtmf6 = { path = "." }
matplotlib = "*"
pandas = "*"
gfortran = "*"
phreeqpy = ">=0.6.1,<1"
pymf6 = ">=1.5.5,<2"
flopy = ">=3.9.5,<4"
typer = ">=0.21.1,<0.22"
