[workspace]
channels = ["hydrocomputing", "conda-forge"]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[dependencies]
python = "3.14.*"
matplotlib = "*"
pandas = "*"
pymf6 = "*"
phreeqcrm = "*"
# phreeqpy = "*"
gfortran = ">=15.2.0,<15.3"
ipython = ">=9.8.0,<10"
modflowapi = ">=0.3.0,<0.4"
pymf6-tools = ">=0.1.3,<0.2"
jupyterlab = ">=4.5.1,<5"
typer = ">=0.21.1,<0.22"
pylint = "*"
setuptools_scm = "*"

[pypi-dependencies]
rtmf6 = { path = ".", editable = true }
phreeqpy = { path = "../../phreeqpy_project/phreeqpy", editable = true }
pymf6 = { path = "../pymf6", editable = true }
pymf6-tools = { path = "../pymf6-tools", editable = true }

[feature.build.dependencies]
twine = ">=5.0.0,<5.1"
# build = ">=0.7.0,<1.0"


[feature.build.tasks]
build-wheel = "python -m build --wheel"
pypi-upload = "python -m  twine upload --config-file=/Users/mike/.pypirc_hydro"

[feature.develop.dependencies]
jupyterlab = '*'
yaml-cpp = '*'
flopy = ">=3.9.5,<4"
modflowapi = ">=0.3.0,<0.4"

[feature.develop.pypi-dependencies]
# pymf6 = { path = "../pymf6", editable = true }
# pymf6-tools = { path = "../pymf6-tools", editable = true }
phreeqpy = { path = "../../phreeqpy_project/phreeqpy", editable = true }


[feature.develop.tasks]
helper_exe = { cmd = "python", cwd = "tests" }
jupyter = { cmd = "jupyter-lab", cwd = "scratch" }
python_dev = "python"
python_phreepy = { cmd = "python", cwd = "tests/phreeqpy" }

[feature.test.dependencies]
pytest = "*"
pytest-md = "*"
pytest-mock = ">=3.15.1,<4"

[feature.test.tasks]
test = "pytest --md=report.md"

[feature.docs.dependencies]
myst-parser = ">=3.0,<4"
sphinx = ">=7.0,<8"
myst-nb = ">=1.1,<2"
jupyterlab = ">=4.5.2,<5"
sphinx-autodoc-typehints = ">=2.0,<3"
furo = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
sphinxcontrib-bibtex = "*"
ansi2html = ">=1.9.2,<2"

# Tasks for documentation are defined in the [feature.docs.tasks] section below.

[feature.docs.tasks.docs-build]
cmd = "sphinx-build -b html source _build/html"
cwd = "docs"
description = "Build documentation"

[feature.docs.tasks.docs-clean]
cmd = "rm -rf _build"
cwd = "docs"
description = "Clean documentation build"

[feature.docs.tasks.docs-serve]
cmd = "python -m http.server -d _build/html 8907"
cwd = "docs"
description = "Serve documentation locally"

[feature.docs.tasks.docs-deploy]
cmd = "zsh deploy_docs.sh"
cwd = "docs/.deploy"
description = "Deploy documentation to https://docs.rtmf6.com/."

[feature.docs.tasks.docs-make-cli-doc]
cmd = "typer rtmf6.main utils docs --output README.md"
cwd = "docs/source/users_guide"
description = "Generate CLI documentation"

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }
develop = { features = ["develop"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[tasks.start]
cmd = "rtmf6"
description = "Start rtmf6"

[tasks.show-version]
cmd = "python -m setuptools_scm"
description = "Show version"

[tasks.update-version]
cmd = "python -m setuptools_scm --force-write-version-files"
description = "Update version files"

[package]
name = "rtmf6"
version = "0.0.5"

[package.build]
backend = { name = "pixi-build-python", version = "0.4.*" }

[package.host-dependencies]
setuptools = "*"

[package.run-dependencies]
rtmf6 = { path = "." }
matplotlib = "*"
pandas = "*"
gfortran = "*"
phreeqpy = ">=0.6.1,<1"
pymf6 = ">=1.5.5,<2"
flopy = ">=3.9.5,<4"
typer = ">=0.21.1,<0.22"
