[project]
name = "ex10"

[models]
flow_models = ["gwf_ex10"]
reaction_models = ["gwt_ex10"]

[[bc_concentrations]]
model_name = "gwf_ex10"
bc_type = "CHD"
file_name = "mf6/gwf_ex10.chd"
src = "rtmf6_sol_number"
dst = "concentration"

[[initial_concentrations]]
model_name = "gwt_ex10"
file_name = "mf6/gwt_ex10.ic"

[[kinetics]]
model_name = "gwt_ex10"
file_name = "rtmf6/init_kinetics.ic"

[[equilibrium_phases]]
model_name = "gwt_ex10"
file_name = "rtmf6/init_equilibrium_phases.ic"

[phreeqcrm]
number_of_threads = 8
chemistry_name = "phreeqcrm/advect.pqi"
database = "phreeqcrm/phreeqc.dat"
#pre_yaml_file = "phreeqcrm/pre.yaml"
#post_yaml_file = "phreeqcrm/post.yaml"
model_yaml_file = "phreeqcrm/model.yaml"

[output]
#equilibrium_phases = "out/equilibrium_phases"
#concentrations = "out/concentrations"
selected_output = "out/selected_output"
